#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDzKhf3CKmVwySZVzK59jik3iuSLoQRS7ttauTwLj/X4TxsrIvKlHFKtKSjfmG0o0brQB+JE20xxNEG8pI+go+24+pbF3du0okk3xhkAGczPr63NWfV0EgwprVqHJCQkKjFpNmodaEO5slqkfyvKaWePwfsRZBVg23HwL8XM+U/Qp1E6tur93mGQphzRYMC3t0KOnEobdj85RpCMUt0Y3RDCNx1SO0rBHEIuFZBpcI11CZDU7bPQ82edvWvqiwKHsGgcTQPTLk7TvdvnPZrX7Tg+VQumQNjnB59twcHJqSn0AZXoAYQfi0nN7zkd1d1CET6x5feVglZv2pjObKQMHwwE0rNEvgdB4XkF6AHZ0X3lqVOq+KbDwMdmA6x+973acNTCygES+jtkonpH2bZDYFTSP22sU31by3tW/Yh9b+GVYZcmIxTr/5uJr0d+Z+wKi0kuf+2tWZ8j/iKnxN4EKJIGUBTAy1yAYN7B6VG55pqNL5JFEuock0XJiy23YD60i/pNqnKSKLywb8TUkfpzxEiM27DgXh716HDDww7T7OVGI3ocKBmfGfl3zGRKdBhsLFo7dxEFUHbH8t9b5pemk+SJDfrdfGImIuVkdj5lHMvlsJf9xbE7tNx4imqBJtfYuK4WclcHPXeXOCBxwjKAMYEYjwZ7zTATHZ6fmABK9xr6w== 1c@Lenovo-PC-4

rancher:
  network:
    interfaces:
      eth*:
        dhcp: true
